### ISSUE TITLE
Calculation of number of columns based on window size is broken on macOS

### ISSUE THREAD

**Issue by melgu** [spacenation/grid#3]
There are way too few rows for the width of the window.

Take the simple example:
```
Grid(0...100) {
    Text("\($0)")
}
```

<img width="659" alt="Bildschirmfoto 2019-08-19 um 10 55 57" src="https://user-images.githubusercontent.com/9601403/63252380-fb9c6580-c26f-11e9-9bdd-eacb78ec2a9d.png">
<img width="1792" alt="Bildschirmfoto 2019-08-19 um 10 56 04" src="https://user-images.githubusercontent.com/9601403/63252384-fdfebf80-c26f-11e9-985c-59e429a811aa.png">

**Comment by ay42** [comment]
@melgu this is now fixes. TextView was not a good example to begin with. It has a predefined min and max width. I replaced it with a RectangleView. You can check it out in the `Examples` folder.
Thank you for pointing this out.
Let me know if there's anything else I can do.
